name: citron-emulator
base: core24
version: '0.6.1'
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
summary: Nintendo Switch Emulator Written In C++
description: |
  Nintendo Switch Emulator Written In C++
grade: stable
confinement: strict
compression: lzo

apps:
  citron-emulator:
    command-chain:
      - snap/command-chain/gpu-2404-wrapper
      - snap/command-chain/desktop-launch6
    command: usr/games/bin/citron
    common-id: org.citron_emu.citron
    environment:
      SNAP_DESKTOP_RUNTIME: $SNAP/kf6
      QT_QPA_PLATFORM: xcb
      GTK_USE_PORTAL: "1"
      QT_VERSION: "6"
    plugs:
      - desktop
      - desktop-legacy
      - unity7
      - opengl
      - wayland
      - x11
      - screen-inhibit-control
      - audio-playback
      - network
      - network-bind
      - home
      - removable-media
      - mount-observe
      - joystick
      - bluez
      - udisks2
      - steam-support

hooks:
  configure:
    command-chain:
      - snap/command-chain/hooks-configure-desktop

slots:
  citron:
    interface: dbus
    bus: session
    name: org.citron_emu.citron

plugs:
  desktop:
    mount-host-font-cache: false
  gtk-2-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  kf6-core24:
    content: kf6-core24-all
    interface: content
    target: $SNAP/kf6
    default-provider: kf6-core24
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404
  shared-memory:
    private: true

package-repositories:
  - type: apt
    url: http://origin.archive.neon.kde.org/user
    suites: [noble]
    components: [main]
    architectures: [amd64]
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D

parts:
  citron-emulator:
    plugin: cmake
    source: https://git.citron-emu.org/citron/emu.git
    build-packages:
      - qt6-base-private-dev
      - libcups2-dev
      - glslang-tools
      - qt6-webengine-dev
      - libavfilter-dev
      - libva-dev
      - qt6-tools-dev
      - qt6-multimedia-dev
      - qt6-base-dev
      - python3-pip
      - libtool
      - autoconf
      - libcpp-httplib-dev
      - catch2
      - libzstd-dev
      - nlohmann-json3-dev
      - liblz4-dev
      - llvm-17-dev
      - libenet-dev
      - libboost-context-dev
      - libboost-dev
      - libsdl2-dev
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libswscale-dev
      - libspeex-dev
      - libdiscord-rpc-dev
      - libglew-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libfmt-dev
      - build-essential
      - git
      - cmake
      - ninja-build
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCITRON_ENABLE_LTO=ON
      - -DCITRON_USE_QT_MULTIMEDIA=ON
      - -DCITRON_USE_QT_WEB_ENGINE=ON
      - -DENABLE_QT_TRANSLATION=ON
      - -DUSE_DISCORD_PRESENCE=OFF
      - -DBUNDLE_SPEEX=ON
      - -DCMAKE_INSTALL_PREFIX=/usr/games/
      - -DTITLE_BAR_FORMAT_RUNNING="Citron | NyKyu v0.6.1 {}"
      - -DTITLE_BAR_FORMAT_IDLE="Citron | NyKyu v0.6.1 {}"
      - -DCITRON_CHECK_SUBMODULES=ON

  command-chain:
    after: [citron-emulator]
    plugin: nil
    source: ./launcher
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/snap
      cp -r command-chain $CRAFT_PART_INSTALL/snap/
      chmod 777 $CRAFT_PART_INSTALL/snap/command-chain/*

layout:
  /usr/share/X11:
    symlink: $SNAP/kf6/usr/share/X11
  /usr/share/qt6:
    symlink: $SNAP/kf6/usr/share/qt6
  /usr/share/libdrm:
    bind: $SNAP/gpu-2404/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/gpu-2404/drirc.d
  /etc/fonts:
    bind: $SNAP/etc/fonts
